import React,{useEffect,useMemo,useState} from "react";
import {Link,useSearchParams} from "react-router-dom";
import {ArrowRight} from "lucide-react";
import {useFleet} from "../hooks/useFleet.js";
import {useBookingSettings} from "../hooks/useBookingSettings.js";

const dateValue=date=>date.toISOString().slice(0,10);
export default function BookingPage(){
 const {vehicles}=useFleet(),settings=useBookingSettings(),[params]=useSearchParams();const available=vehicles.filter(car=>car.available);const minDate=useMemo(()=>{const date=new Date();date.setDate(date.getDate()+settings.minimumNoticeDays);return dateValue(date)},[settings.minimumNoticeDays]);
 const[step,setStep]=useState(1),[done,setDone]=useState(false),[form,setForm]=useState({service:params.get("service")||"",vehicle:params.get("vehicle")||"",date:params.get("date")||"",duration:params.get("duration")||"",name:"",email:"",phone:""});
 useEffect(()=>setForm(current=>({...current,service:settings.services.includes(current.service)?current.service:settings.services[0]||"",duration:settings.durations.includes(current.duration)?current.duration:settings.durations[0]||"",vehicle:available.some(car=>`${car.brand} ${car.name}`===current.vehicle)?current.vehicle:available[0]?`${available[0].brand} ${available[0].name}`:""})),[settings.services,settings.durations,available.length]);
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 if(done)return <section className="booking-success"><div className="shell"><span>{settings.confirmationKicker}</span><h1>{settings.confirmationTitleLine1}<br/><i>{settings.confirmationTitleLine2}</i></h1><p>Thanks {form.name||"there"}. {settings.confirmationMessage}</p><Link to="/">RETURN HOME <ArrowRight/></Link></div></section>;
 return <section className="booking-page"><div className="shell booking-page-grid"><div className="booking-aside"><div className="section-no">{settings.kicker}</div><h1>{settings.titleLine1}<br/><i>{settings.titleLine2}</i></h1><p>{settings.intro}</p><div className="step-list">{["EXPERIENCE","DATES","YOUR DETAILS"].map((label,index)=><div key={label} className={step===index+1?"active":step>index+1?"done":""}><span>0{index+1}</span>{label}</div>)}</div></div><form className="booking-wizard" onSubmit={event=>{event.preventDefault();if(step<3)setStep(step+1);else setDone(true)}}>
 {step===1&&<div className="wizard-panel"><small>STEP 01</small><h2>CHOOSE YOUR EXPERIENCE</h2><label>SERVICE<select required value={form.service} onChange={event=>set("service",event.target.value)}>{settings.services.map(service=><option key={service}>{service}</option>)}</select></label><label>VEHICLE<select required value={form.vehicle} onChange={event=>set("vehicle",event.target.value)}>{available.map(car=><option key={car.id}>{car.brand} {car.name}</option>)}</select></label></div>}
 {step===2&&<div className="wizard-panel"><small>STEP 02</small><h2>WHEN ARE YOU MOVING?</h2><label>START DATE<input required type="date" min={minDate} value={form.date} onChange={event=>set("date",event.target.value)}/><span className="field-help">Minimum notice: {settings.minimumNoticeDays} day{settings.minimumNoticeDays===1?"":"s"}</span></label><label>DURATION<select required value={form.duration} onChange={event=>set("duration",event.target.value)}>{settings.durations.map(duration=><option key={duration}>{duration}</option>)}</select></label></div>}
 {step===3&&<div className="wizard-panel"><small>STEP 03</small><h2>YOUR DETAILS</h2><label>FULL NAME<input required autoComplete="name" value={form.name} onChange={event=>set("name",event.target.value)} placeholder="Your name"/></label><label>EMAIL<input required type="email" autoComplete="email" value={form.email} onChange={event=>set("email",event.target.value)} placeholder="you@email.com"/></label><label>PHONE<input required type="tel" autoComplete="tel" value={form.phone} onChange={event=>set("phone",event.target.value)} placeholder="+44"/></label></div>}
 <div className="wizard-actions">{step>1&&<button type="button" className="back" onClick={()=>setStep(step-1)}>← BACK</button>}<button type="submit" className="next">{step===3?"SEND REQUEST":"CONTINUE"}<ArrowRight/></button></div></form></div></section>;
}
